//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teklican.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int id { get; set; }
        public string usernname { get; set; }
        public string email { get; set; }
        public string pwd { get; set; }
        public string repwd { get; set; }
        public Nullable<int> phanquyen { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
    }
}
