//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teklican.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrdersDetails = new HashSet<OrdersDetail>();
        }
    
        public int id_Product { get; set; }
        public string name { get; set; }
        public Nullable<int> id_ProductType { get; set; }
        public Nullable<decimal> price { get; set; }
        public string description { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<int> inventory { get; set; }
        public string img { get; set; }
        public Nullable<int> tax { get; set; }
        public string small_img1 { get; set; }
        public string small_img2 { get; set; }
        public string small_img3 { get; set; }
        public string small_img4 { get; set; }
        public string small_img5 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdersDetail> OrdersDetails { get; set; }
        public virtual ProductType ProductType { get; set; }
    }
}
